---
- hosts: myhosts
  remote_user: root
  vars:
    jar_file: spring-petclinic-3.2.0-SNAPSHOT.jar
  tasks:
    - name: Copy jar file
      copy:
        src: "/target/"
        dest: "/app/"
    - name: Start jar file
      shell: java -jar {{ jar_file }}
